version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - my-network  # Attach mongo_db service to my-network

  swimlane:
    build: .
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo_db:27017/database  # Use service name as hostname
    depends_on:
      - mongo_db
    networks:
      - my-network  # Attach swimlane service to my-network

volumes:
  mongo_db: {}

networks:
  my-network:  # Define a custom network
    driver: bridge  # Use bridge network mode (default)
