nodejs:
  image:
    repository: maniengg/swimlane
    tag: latest
    
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  environment:
    MONGODB_URL: "mongodb://mongodb-service:27017/database"
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
  resources: {}

mongodb:
  image:
    repository: mongo
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 27017
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  resources: {}
